//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Modules/Player/GameplayData/Input/GameInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInput"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""5759a6b9-01d4-43e7-a926-7645a5446a6d"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ada3f6af-b73a-4677-9f31-9e6590ab54d0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActiveItemUse"",
                    ""type"": ""Button"",
                    ""id"": ""510ea17f-edb9-4ef3-a72a-7731dc2519e8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""25554a75-b92e-4e6a-a01c-2fe8ae5a511b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ItemSwitch"",
                    ""type"": ""Button"",
                    ""id"": ""eb2433d6-0cf8-46a1-a577-cd231797831a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ReloadGun"",
                    ""type"": ""Button"",
                    ""id"": ""92189fb7-6d87-45d8-8b48-c3a31a4b0d03"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PaceControl"",
                    ""type"": ""Button"",
                    ""id"": ""f6e3aa7e-e498-4fc1-97d4-e69e412da29d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""Button"",
                    ""id"": ""1cfc97d6-6078-4047-831f-69abd6234b03"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ItemPickup"",
                    ""type"": ""Button"",
                    ""id"": ""95e7b3c2-46d5-4fe1-bcb3-1a95bb85f1d8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ItemSwitchLR"",
                    ""type"": ""Button"",
                    ""id"": ""24ecfabc-2de4-4abd-ade0-eaf66708d357"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TargetSwitchLR"",
                    ""type"": ""Value"",
                    ""id"": ""eff47b41-57b8-4832-979c-78c1601e6d61"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TargetSwitchRSFlick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""d9fa0292-8fb8-462e-bfb5-027ba64116ee"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TargetSwitchButton"",
                    ""type"": ""Button"",
                    ""id"": ""50e5a0c3-7f47-48fd-969f-2ecf2cefa9f4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ItemDrop"",
                    ""type"": ""Button"",
                    ""id"": ""db02ccab-6341-48e3-8450-32a39eb8a86f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""57d872b9-10a4-4c57-93c6-ab9a6c7dc562"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ability1"",
                    ""type"": ""Button"",
                    ""id"": ""96254724-f877-4b9a-93f1-5e1d211b86b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ability2"",
                    ""type"": ""Button"",
                    ""id"": ""e12db829-b964-4adc-91c9-748c1564f5c1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ability3"",
                    ""type"": ""Button"",
                    ""id"": ""12d64b8b-39bd-4500-b936-94bf344e389e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ability4"",
                    ""type"": ""Button"",
                    ""id"": ""0191f9d4-c8f3-419d-a7fc-e45bacdf3358"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Ability5"",
                    ""type"": ""Button"",
                    ""id"": ""6e592e13-08ea-4cc9-ab18-ec2c78975547"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Test_ApplyDamage"",
                    ""type"": ""Button"",
                    ""id"": ""d64c47b2-3964-4ed0-b19b-d9c6f285d6f8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7588108e-76b4-4704-a5c6-bdde05d97ce3"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""ef8bfb71-67c3-4eb9-9a0f-476f3756b1b7"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ff60f567-8d7f-403d-88bf-8750c6799f29"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM 1;KBM"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7fd96799-a26d-415d-9d13-8285b4b4e1dd"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM 1;KBM"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""7f6fb862-d03d-4edf-8c30-6b063c02860e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM 1;KBM"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e4593c37-b82d-42c0-8a44-f91c5936e9cf"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM 1;KBM"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""76878068-62e0-4406-9ca0-c70b3a994b92"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActiveItemUse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1fb22ebb-ecf2-4ebc-a2d1-aebc8716cfa9"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""ActiveItemUse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""af8bcf0f-3f27-4708-b457-d58157d2043b"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActiveItemUse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ee9b5ee2-ab2a-4b99-88e5-c2deb5766376"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActiveItemUse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""676f2e0f-47f1-4428-abeb-bf48cfd4c407"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""027155f4-0f17-438c-ac4c-7af9a616ffea"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25e3aa4a-02c8-4c5a-a207-5f06a1fa4ddb"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ItemSwitch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""81b2016c-5448-4b6b-bc82-bbe5b035ef6e"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ItemSwitch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""91174d18-3d3f-4b78-8460-cf2ce1e9be37"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReloadGun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8250798a-103d-4bb5-9fef-aa9369b9bc8b"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReloadGun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c77db502-73f4-4c15-9b30-450ec3f365fb"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PaceControl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ec53064b-8701-4e74-8915-fcf0d1cfde36"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PaceControl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41e55b96-562c-4de0-8d6c-142e05501051"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0c33884-854e-473d-b4b2-21a7ce62b5d3"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ItemPickup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a8d54a8-08f9-42ea-83e7-5657a41c7391"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ItemPickup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""LRTargetSwitchKeyboard"",
                    ""id"": ""4abf556d-7a96-4ad9-92ff-ecb9349f154c"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TargetSwitchLR"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""0475b3b3-83d9-4dbb-a08e-31401bfef0e8"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TargetSwitchLR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""b70ca9fb-66e3-46ed-b789-67138fb37005"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TargetSwitchLR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""LRTargetSwitchGamepad"",
                    ""id"": ""27156edb-9208-4b52-88dc-94f97354a018"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TargetSwitchLR"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""52ea8472-cc3f-482e-b41e-4d51c304c341"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TargetSwitchLR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""15fe2462-195f-43fc-8e27-fbc668a61bd8"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TargetSwitchLR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""df5253b5-1a00-44b7-876f-c0e2253e2db8"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TargetSwitchRSFlick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""LeftRightSwitch_Keyboard"",
                    ""id"": ""16633e4a-b931-49be-8ad2-565bfef46bb2"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ItemSwitchLR"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""6eab7574-8c93-4cec-8e9e-f7e037abc630"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ItemSwitchLR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""4c6505c7-c4bd-45ea-a2df-bb594591eb7a"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ItemSwitchLR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""LeftRightSwitch_Gamepad"",
                    ""id"": ""e6a492dd-7a9c-4c36-ab0f-92c6aa37f79f"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ItemSwitchLR"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""e068226f-869f-42b0-ad38-537a35be6dd2"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ItemSwitchLR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""744c1e69-626b-4aff-b643-f9ae85ee03ef"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ItemSwitchLR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""ccbe7286-66cf-4c4e-a8be-017bd163bc89"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TargetSwitchButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f2b94c20-12ed-4b3a-99fc-2699138cae1c"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TargetSwitchButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""40850ed1-8ee5-44c2-8f7a-498116cfd265"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ItemDrop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""37dee908-dc92-42b1-a610-f659e15a62af"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70fc50b6-3430-483e-88d7-479a8c5f79b5"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ability1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4578e6c4-6504-45fc-b7fb-058eba8387cf"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ability1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25f36838-9ccf-4a35-8dd5-ef1928d09ac2"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ability2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""073ce34b-390f-4986-96cb-646a62c06ead"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ability2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""daeb5a61-2d03-422c-8b70-137a59fa883c"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ability3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80a8dea5-5ac2-437a-b7b2-889203ffd281"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ability3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3307916c-5821-4264-beb5-3c0c8e6e07cf"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ability4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a20ddbb-3ac9-4c14-b8b0-040ae16169c3"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ability5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0dc5c9fc-724d-454d-999d-d0d0ecb143f8"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Test_ApplyDamage"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""KBM"",
            ""bindingGroup"": ""KBM"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_Movement = m_Gameplay.FindAction("Movement", throwIfNotFound: true);
        m_Gameplay_ActiveItemUse = m_Gameplay.FindAction("ActiveItemUse", throwIfNotFound: true);
        m_Gameplay_Sprint = m_Gameplay.FindAction("Sprint", throwIfNotFound: true);
        m_Gameplay_ItemSwitch = m_Gameplay.FindAction("ItemSwitch", throwIfNotFound: true);
        m_Gameplay_ReloadGun = m_Gameplay.FindAction("ReloadGun", throwIfNotFound: true);
        m_Gameplay_PaceControl = m_Gameplay.FindAction("PaceControl", throwIfNotFound: true);
        m_Gameplay_Aim = m_Gameplay.FindAction("Aim", throwIfNotFound: true);
        m_Gameplay_ItemPickup = m_Gameplay.FindAction("ItemPickup", throwIfNotFound: true);
        m_Gameplay_ItemSwitchLR = m_Gameplay.FindAction("ItemSwitchLR", throwIfNotFound: true);
        m_Gameplay_TargetSwitchLR = m_Gameplay.FindAction("TargetSwitchLR", throwIfNotFound: true);
        m_Gameplay_TargetSwitchRSFlick = m_Gameplay.FindAction("TargetSwitchRSFlick", throwIfNotFound: true);
        m_Gameplay_TargetSwitchButton = m_Gameplay.FindAction("TargetSwitchButton", throwIfNotFound: true);
        m_Gameplay_ItemDrop = m_Gameplay.FindAction("ItemDrop", throwIfNotFound: true);
        m_Gameplay_Crouch = m_Gameplay.FindAction("Crouch", throwIfNotFound: true);
        m_Gameplay_Ability1 = m_Gameplay.FindAction("Ability1", throwIfNotFound: true);
        m_Gameplay_Ability2 = m_Gameplay.FindAction("Ability2", throwIfNotFound: true);
        m_Gameplay_Ability3 = m_Gameplay.FindAction("Ability3", throwIfNotFound: true);
        m_Gameplay_Ability4 = m_Gameplay.FindAction("Ability4", throwIfNotFound: true);
        m_Gameplay_Ability5 = m_Gameplay.FindAction("Ability5", throwIfNotFound: true);
        m_Gameplay_Test_ApplyDamage = m_Gameplay.FindAction("Test_ApplyDamage", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
    private readonly InputAction m_Gameplay_Movement;
    private readonly InputAction m_Gameplay_ActiveItemUse;
    private readonly InputAction m_Gameplay_Sprint;
    private readonly InputAction m_Gameplay_ItemSwitch;
    private readonly InputAction m_Gameplay_ReloadGun;
    private readonly InputAction m_Gameplay_PaceControl;
    private readonly InputAction m_Gameplay_Aim;
    private readonly InputAction m_Gameplay_ItemPickup;
    private readonly InputAction m_Gameplay_ItemSwitchLR;
    private readonly InputAction m_Gameplay_TargetSwitchLR;
    private readonly InputAction m_Gameplay_TargetSwitchRSFlick;
    private readonly InputAction m_Gameplay_TargetSwitchButton;
    private readonly InputAction m_Gameplay_ItemDrop;
    private readonly InputAction m_Gameplay_Crouch;
    private readonly InputAction m_Gameplay_Ability1;
    private readonly InputAction m_Gameplay_Ability2;
    private readonly InputAction m_Gameplay_Ability3;
    private readonly InputAction m_Gameplay_Ability4;
    private readonly InputAction m_Gameplay_Ability5;
    private readonly InputAction m_Gameplay_Test_ApplyDamage;
    public struct GameplayActions
    {
        private @GameInput m_Wrapper;
        public GameplayActions(@GameInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Gameplay_Movement;
        public InputAction @ActiveItemUse => m_Wrapper.m_Gameplay_ActiveItemUse;
        public InputAction @Sprint => m_Wrapper.m_Gameplay_Sprint;
        public InputAction @ItemSwitch => m_Wrapper.m_Gameplay_ItemSwitch;
        public InputAction @ReloadGun => m_Wrapper.m_Gameplay_ReloadGun;
        public InputAction @PaceControl => m_Wrapper.m_Gameplay_PaceControl;
        public InputAction @Aim => m_Wrapper.m_Gameplay_Aim;
        public InputAction @ItemPickup => m_Wrapper.m_Gameplay_ItemPickup;
        public InputAction @ItemSwitchLR => m_Wrapper.m_Gameplay_ItemSwitchLR;
        public InputAction @TargetSwitchLR => m_Wrapper.m_Gameplay_TargetSwitchLR;
        public InputAction @TargetSwitchRSFlick => m_Wrapper.m_Gameplay_TargetSwitchRSFlick;
        public InputAction @TargetSwitchButton => m_Wrapper.m_Gameplay_TargetSwitchButton;
        public InputAction @ItemDrop => m_Wrapper.m_Gameplay_ItemDrop;
        public InputAction @Crouch => m_Wrapper.m_Gameplay_Crouch;
        public InputAction @Ability1 => m_Wrapper.m_Gameplay_Ability1;
        public InputAction @Ability2 => m_Wrapper.m_Gameplay_Ability2;
        public InputAction @Ability3 => m_Wrapper.m_Gameplay_Ability3;
        public InputAction @Ability4 => m_Wrapper.m_Gameplay_Ability4;
        public InputAction @Ability5 => m_Wrapper.m_Gameplay_Ability5;
        public InputAction @Test_ApplyDamage => m_Wrapper.m_Gameplay_Test_ApplyDamage;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @ActiveItemUse.started += instance.OnActiveItemUse;
            @ActiveItemUse.performed += instance.OnActiveItemUse;
            @ActiveItemUse.canceled += instance.OnActiveItemUse;
            @Sprint.started += instance.OnSprint;
            @Sprint.performed += instance.OnSprint;
            @Sprint.canceled += instance.OnSprint;
            @ItemSwitch.started += instance.OnItemSwitch;
            @ItemSwitch.performed += instance.OnItemSwitch;
            @ItemSwitch.canceled += instance.OnItemSwitch;
            @ReloadGun.started += instance.OnReloadGun;
            @ReloadGun.performed += instance.OnReloadGun;
            @ReloadGun.canceled += instance.OnReloadGun;
            @PaceControl.started += instance.OnPaceControl;
            @PaceControl.performed += instance.OnPaceControl;
            @PaceControl.canceled += instance.OnPaceControl;
            @Aim.started += instance.OnAim;
            @Aim.performed += instance.OnAim;
            @Aim.canceled += instance.OnAim;
            @ItemPickup.started += instance.OnItemPickup;
            @ItemPickup.performed += instance.OnItemPickup;
            @ItemPickup.canceled += instance.OnItemPickup;
            @ItemSwitchLR.started += instance.OnItemSwitchLR;
            @ItemSwitchLR.performed += instance.OnItemSwitchLR;
            @ItemSwitchLR.canceled += instance.OnItemSwitchLR;
            @TargetSwitchLR.started += instance.OnTargetSwitchLR;
            @TargetSwitchLR.performed += instance.OnTargetSwitchLR;
            @TargetSwitchLR.canceled += instance.OnTargetSwitchLR;
            @TargetSwitchRSFlick.started += instance.OnTargetSwitchRSFlick;
            @TargetSwitchRSFlick.performed += instance.OnTargetSwitchRSFlick;
            @TargetSwitchRSFlick.canceled += instance.OnTargetSwitchRSFlick;
            @TargetSwitchButton.started += instance.OnTargetSwitchButton;
            @TargetSwitchButton.performed += instance.OnTargetSwitchButton;
            @TargetSwitchButton.canceled += instance.OnTargetSwitchButton;
            @ItemDrop.started += instance.OnItemDrop;
            @ItemDrop.performed += instance.OnItemDrop;
            @ItemDrop.canceled += instance.OnItemDrop;
            @Crouch.started += instance.OnCrouch;
            @Crouch.performed += instance.OnCrouch;
            @Crouch.canceled += instance.OnCrouch;
            @Ability1.started += instance.OnAbility1;
            @Ability1.performed += instance.OnAbility1;
            @Ability1.canceled += instance.OnAbility1;
            @Ability2.started += instance.OnAbility2;
            @Ability2.performed += instance.OnAbility2;
            @Ability2.canceled += instance.OnAbility2;
            @Ability3.started += instance.OnAbility3;
            @Ability3.performed += instance.OnAbility3;
            @Ability3.canceled += instance.OnAbility3;
            @Ability4.started += instance.OnAbility4;
            @Ability4.performed += instance.OnAbility4;
            @Ability4.canceled += instance.OnAbility4;
            @Ability5.started += instance.OnAbility5;
            @Ability5.performed += instance.OnAbility5;
            @Ability5.canceled += instance.OnAbility5;
            @Test_ApplyDamage.started += instance.OnTest_ApplyDamage;
            @Test_ApplyDamage.performed += instance.OnTest_ApplyDamage;
            @Test_ApplyDamage.canceled += instance.OnTest_ApplyDamage;
        }

        private void UnregisterCallbacks(IGameplayActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @ActiveItemUse.started -= instance.OnActiveItemUse;
            @ActiveItemUse.performed -= instance.OnActiveItemUse;
            @ActiveItemUse.canceled -= instance.OnActiveItemUse;
            @Sprint.started -= instance.OnSprint;
            @Sprint.performed -= instance.OnSprint;
            @Sprint.canceled -= instance.OnSprint;
            @ItemSwitch.started -= instance.OnItemSwitch;
            @ItemSwitch.performed -= instance.OnItemSwitch;
            @ItemSwitch.canceled -= instance.OnItemSwitch;
            @ReloadGun.started -= instance.OnReloadGun;
            @ReloadGun.performed -= instance.OnReloadGun;
            @ReloadGun.canceled -= instance.OnReloadGun;
            @PaceControl.started -= instance.OnPaceControl;
            @PaceControl.performed -= instance.OnPaceControl;
            @PaceControl.canceled -= instance.OnPaceControl;
            @Aim.started -= instance.OnAim;
            @Aim.performed -= instance.OnAim;
            @Aim.canceled -= instance.OnAim;
            @ItemPickup.started -= instance.OnItemPickup;
            @ItemPickup.performed -= instance.OnItemPickup;
            @ItemPickup.canceled -= instance.OnItemPickup;
            @ItemSwitchLR.started -= instance.OnItemSwitchLR;
            @ItemSwitchLR.performed -= instance.OnItemSwitchLR;
            @ItemSwitchLR.canceled -= instance.OnItemSwitchLR;
            @TargetSwitchLR.started -= instance.OnTargetSwitchLR;
            @TargetSwitchLR.performed -= instance.OnTargetSwitchLR;
            @TargetSwitchLR.canceled -= instance.OnTargetSwitchLR;
            @TargetSwitchRSFlick.started -= instance.OnTargetSwitchRSFlick;
            @TargetSwitchRSFlick.performed -= instance.OnTargetSwitchRSFlick;
            @TargetSwitchRSFlick.canceled -= instance.OnTargetSwitchRSFlick;
            @TargetSwitchButton.started -= instance.OnTargetSwitchButton;
            @TargetSwitchButton.performed -= instance.OnTargetSwitchButton;
            @TargetSwitchButton.canceled -= instance.OnTargetSwitchButton;
            @ItemDrop.started -= instance.OnItemDrop;
            @ItemDrop.performed -= instance.OnItemDrop;
            @ItemDrop.canceled -= instance.OnItemDrop;
            @Crouch.started -= instance.OnCrouch;
            @Crouch.performed -= instance.OnCrouch;
            @Crouch.canceled -= instance.OnCrouch;
            @Ability1.started -= instance.OnAbility1;
            @Ability1.performed -= instance.OnAbility1;
            @Ability1.canceled -= instance.OnAbility1;
            @Ability2.started -= instance.OnAbility2;
            @Ability2.performed -= instance.OnAbility2;
            @Ability2.canceled -= instance.OnAbility2;
            @Ability3.started -= instance.OnAbility3;
            @Ability3.performed -= instance.OnAbility3;
            @Ability3.canceled -= instance.OnAbility3;
            @Ability4.started -= instance.OnAbility4;
            @Ability4.performed -= instance.OnAbility4;
            @Ability4.canceled -= instance.OnAbility4;
            @Ability5.started -= instance.OnAbility5;
            @Ability5.performed -= instance.OnAbility5;
            @Ability5.canceled -= instance.OnAbility5;
            @Test_ApplyDamage.started -= instance.OnTest_ApplyDamage;
            @Test_ApplyDamage.performed -= instance.OnTest_ApplyDamage;
            @Test_ApplyDamage.canceled -= instance.OnTest_ApplyDamage;
        }

        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    private int m_KBMSchemeIndex = -1;
    public InputControlScheme KBMScheme
    {
        get
        {
            if (m_KBMSchemeIndex == -1) m_KBMSchemeIndex = asset.FindControlSchemeIndex("KBM");
            return asset.controlSchemes[m_KBMSchemeIndex];
        }
    }
    public interface IGameplayActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnActiveItemUse(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnItemSwitch(InputAction.CallbackContext context);
        void OnReloadGun(InputAction.CallbackContext context);
        void OnPaceControl(InputAction.CallbackContext context);
        void OnAim(InputAction.CallbackContext context);
        void OnItemPickup(InputAction.CallbackContext context);
        void OnItemSwitchLR(InputAction.CallbackContext context);
        void OnTargetSwitchLR(InputAction.CallbackContext context);
        void OnTargetSwitchRSFlick(InputAction.CallbackContext context);
        void OnTargetSwitchButton(InputAction.CallbackContext context);
        void OnItemDrop(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnAbility1(InputAction.CallbackContext context);
        void OnAbility2(InputAction.CallbackContext context);
        void OnAbility3(InputAction.CallbackContext context);
        void OnAbility4(InputAction.CallbackContext context);
        void OnAbility5(InputAction.CallbackContext context);
        void OnTest_ApplyDamage(InputAction.CallbackContext context);
    }
}
